# Lambda Functions - Lab

## Introduction

In this lab, you'll get some hands-on practice creating and using lambda functions.

## Objectives

In this lab you will:

* Create lambda functions to use as arguments of other functions   
* Use the `.map()` or `.apply()` method to apply a function to a pandas series or DataFrame

## Lambda Functions

In [1]:
!git clone https://github.com/dbvimpec/dsc-lambda-functions-lab

Cloning into 'dsc-lambda-functions-lab'...
remote: Enumerating objects: 184, done.
remote: Counting objects: 100% (51/51), done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 184 (delta 48), reused 39 (delta 39), pack-reused 133 (from 1)
Receiving objects: 100% (184/184), 1.21 MiB | 9.47 MiB/s, done.
Resolving deltas: 100% (112/112), done.

In [2]:
import pandas as pd
df = pd.read_csv('dsc-lambda-functions-lab/Yelp_Reviews.csv', index_col=0)
df.head(2)

,business_id,cool,date,funny,review_id,stars,text,useful,user_id
1,pomGBqfbxcqPv14c3XH-ZQ,0,2012-11-13,0,dDl8zu1vWPdKGihJrwQbpw,5,I love this place! My fiance And I go here atl...,0,msQe1u7Z_XuqjGoqhB0J5g
2,jtQARsP6P-LbkyjbO1qNGg,1,2014-10-23,1,LZp4UX5zK3e-c5ZGSeo3kA,1,Terrible. Dry corn bread. Rib tips were all fa...,3,msQe1u7Z_XuqjGoqhB0J5g

## Simple arithmetic

Use a lambda function to create a new column called `'stars_squared'` by squaring the stars column.

In [3]:
# Your code here

df['stars_squared'] = df['stars'].map(lambda x: x**2)
df.head()

,business_id,cool,date,funny,review_id,stars,text,useful,user_id,stars_squared
1,pomGBqfbxcqPv14c3XH-ZQ,0,2012-11-13,0,dDl8zu1vWPdKGihJrwQbpw,5,I love this place! My fiance And I go here atl...,0,msQe1u7Z_XuqjGoqhB0J5g,25
2,jtQARsP6P-LbkyjbO1qNGg,1,2014-10-23,1,LZp4UX5zK3e-c5ZGSeo3kA,1,Terrible. Dry corn bread. Rib tips were all fa...,3,msQe1u7Z_XuqjGoqhB0J5g,1
4,Ums3gaP2qM3W1XcA5r6SsQ,0,2014-09-05,0,jsDu6QEJHbwP2Blom1PLCA,5,Delicious healthy food. The steak is amazing. ...,0,msQe1u7Z_XuqjGoqhB0J5g,25
5,vgfcTvK81oD4r50NMjU2Ag,0,2011-02-25,0,pfavA0hr3nyqO61oupj-lA,1,This place sucks. The customer service is horr...,2,msQe1u7Z_XuqjGoqhB0J5g,1
10,yFumR3CWzpfvTH2FCthvVw,0,2016-06-15,0,STiFMww2z31siPY7BWNC2g,5,I have been an Emerald Club member for a numbe...,0,TlvV-xJhmh7LCwJYXkV-cg,25

## Dates
Select the month from the date string using a lambda function.

In [5]:
# Your code here

df['date'].map(lambda x: x[5:7]).head()

1     11
2     10
4     09
5     02
10    06
Name: date, dtype: object

## What is the average number of words for a yelp review?
Do this with a single line of code.

In [8]:
# Your code here

df['text'].map(lambda x: len(x.split())).mean()

77.06551724137931

## Create a new column for the number of words in the review

In [10]:
# Your code here
df['Review_num_words'] = df['text'].map(lambda x: len(x.split()))
df.head(2)

,business_id,cool,date,funny,review_id,stars,text,useful,user_id,stars_squared,Review_num_words
1,pomGBqfbxcqPv14c3XH-ZQ,0,2012-11-13,0,dDl8zu1vWPdKGihJrwQbpw,5,I love this place! My fiance And I go here atl...,0,msQe1u7Z_XuqjGoqhB0J5g,25,58
2,jtQARsP6P-LbkyjbO1qNGg,1,2014-10-23,1,LZp4UX5zK3e-c5ZGSeo3kA,1,Terrible. Dry corn bread. Rib tips were all fa...,3,msQe1u7Z_XuqjGoqhB0J5g,1,30

## Rewrite the following as a lambda function

Create a new column `'Review_Length'` by applying this lambda function to the `'Review_num_words'` column.

In [11]:
# Rewrite the following function as a lambda function
def rewrite_as_lambda(value):
    if len(value) > 50:
        return 'Short'
    elif len(value) < 80:
        return 'Medium'
    else:
        return 'Long'
# Hint: nest your if, else conditionals

df['Review_length'] = df['Review_num_words'].map(lambda x: 'Short' if x < 50 else ('Medium' if x < 80 else 'Long'))
df['Review_length'].value_counts(normalize=True)

Review_length
Short     0.493103
Long      0.294636
Medium    0.212261
Name: proportion, dtype: float64

## Level Up: Dates Advanced
<img src="https://github.com/dbvimpec/dsc-lambda-functions-lab/blob/master/images/world_map.png?raw=1" width="600">  

Print the first five rows of the `'date'` column.

In [12]:
# Your code here
df['date'].head()

1     2012-11-13
2     2014-10-23
4     2014-09-05
5     2011-02-25
10    2016-06-15
Name: date, dtype: object

Overwrite the `'date'` column by reordering the month and day from `YYYY-MM-DD` to `DD-MM-YYYY`. Try to do this using a lambda function.

In [16]:
# Your code here
df['date'] = df['date'].map(lambda x: '{}-{}-{}'.format(x[-2:], x[5:7], x[:4]))
df['date'].head()

1     13-11-2012
2     23-10-2014
4     05-09-2014
5     25-02-2011
10    15-06-2016
Name: date, dtype: object

## Summary

Hopefully, you're getting the hang of lambda functions now! It's important not to overuse them - it will often make more sense to define a function so that it's reusable elsewhere. But whenever you need to quickly apply some simple processing to a collection of data you have a new technique that will help you to do just that. It'll also be useful if you're reading someone else's code that happens to use lambdas.